packages:
  - client

overrides:
  "app-builder-lib>@electron/get": 3.1.0

allowBuilds:
  better-sqlite3: true
  core-js: true
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
