let shelljs = require('shelljs')

console.log('entry gui directory')
shelljs.cd('./gui')
console.log('run `npm run build`')
shelljs.exec('npm run build')
console.log('return root category`')
shelljs.cd('..')
console.log('remove old static`')
shelljs.rm('-rf', './dist/gui')
shelljs.mkdir('-p', './dist/gui/dist')
console.log('copy new static`')
shelljs.cp('./gui/dist/*', './dist/gui/dist/')
console.log('gui 构建完毕')
