let shelljs = require('shelljs')

console.log('1. build server')
shelljs.exec('npm run build')
console.log('server build complete')
console.log('2. build gui')
console.log('entry client directory')
shelljs.cd('./client')
console.log('run `npm run build`')
shelljs.exec('npm run build')
console.log('return to root category`')
shelljs.cd('..')
console.log('remove old static`')
shelljs.rm('-rf', './dist/client')
shelljs.mkdir('-p', './dist/client/dist')
console.log('copy new static`')
console.log('client build complete')
console.log('3. move resource')
shelljs.cp('./client/dist/*', './dist/client/dist/')
// 将dist目录迁移到app目录中, 只发布需要的部分
shelljs.mkdir('-p', './app/dist')
shelljs.cp('./dist/*', './app/dist/')
console.log('4. cd 2 category app and run make')
shelljs.cd('./app')
shelljs.exec('npm run make')
